### ISSUE TITLE
Javascript arcTo can be negative

### ISSUE THREAD

**Issue by doctor-g** [doctor-g/social-startup-game#23]
Seen in HTML build: 
WARN: Frame tick exception: (IndexSizeError) : Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-3.71321) is negative. JavaScriptException__gwt$backingJsError: Errorcause: nulldescription_0: ": Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-3.71321) is negative."detailMessage: nulldisableSuppression: falsee: DOMException: Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-3.71321) is negative.
    at Error (native)
    at $arcTo (sim-0.js:3156:15)
    at $fillRoundRect (sim-0.js:18476:3)
    at instantiate_6 [as instantiate] (sim-0.js:25478:5)
    at $layout (sim-0.js:9435:52)
    at layout_0 [as layout] (sim-0.js:9541:3)
    at $validate (sim-0.js:9479:17)
    at validate (sim-0.js:9574:3)
    at $layout_0 (sim-0.js:10118:29)
    at layout_4 (sim-0.js:10162:3)message_0: "(IndexSizeError) : Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-3.71321) is negative."name_0: "IndexSizeError"stackTrace: Array[16]__proto__: F

**Comment by doctor-g** [comment]
This has not come up in a long time, so I am closing this issue.
